# ********RoostGPT********

# Test generated by RoostGPT for test Karate-CSV using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /aisp/accounts/{accountId}_get for http method type GET 
# RoostTestHash=8067523cbb
# 
# 

# ********RoostGPT********
Feature: Testing /aisp/accounts/{accountId} endpoint

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * def headers = {Authorization: '#('Bearer ' + authToken)', 'x-fapi-auth-date': 'Sun, 10 Sep 2017 19:43:31 UTC', 'x-fapi-customer-ip-address': '169.254.169.254', 'x-fapi-interaction-id': '', 'Accept-Language': ''}

  Scenario Outline: Verify successful GET request to /aisp/accounts/{accountId} endpoint
    Given path 'aisp/accounts/', '<accountId>'
    And headers headers
    When method get
    Then status 200
    And match responseHeaders['Content-Type'] == 'application/json'
    And match response.data.account contains {accountId: '#string', accountNumber: '#string', accountType: '#string', accountSubType: '#string', productName: '#string', accountStatus: '#string', currency: '#string'}
    And match response.links contains {self: '#string'}

    Examples:
      | read('aisp_accounts_accountId_get.csv') |

  Scenario Outline: Verify unsuccessful GET request to /aisp/accounts/{accountId} endpoint
    Given path 'aisp/accounts/', '<accountId>'
    And headers headers
    When method get
    Then status <statusCode>
    And match responseHeaders['Content-Type'] == 'application/json'

    Examples:
      | read('aisp_accounts_accountId_get.csv') |
