# ********RoostGPT********

# Test generated by RoostGPT for test Karate-CSV using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /aisp/accounts/{accountId}/balances_get for http method type GET 
# RoostTestHash=0095e68c59
# 
# 

# ********RoostGPT********
Feature: Karate Test for RESTful API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * configure headers = {Authorization: '#(karate.properties['AUTH_TOKEN'])', 'x-fapi-auth-date': 'Sun, 10 Sep 2017 19:43:31 UTC', 'x-fapi-customer-ip-address': '169.254.169.254', 'x-fapi-interaction-id': 'unique-id', 'Accept-Language': 'en-US'}

  Scenario Outline: Test GET method for endpoint /aisp/accounts/{accountId}/balances
    Given path 'aisp', 'accounts', '<accountId>', 'balances'
    When method get
    Then status <statusCode>

    Examples:
      | read('aisp_accounts_accountId_balances_get.csv') |

  Scenario Outline: Test response headers and body
    Given path 'aisp', 'accounts', '<accountId>', 'balances'
    When method get
    Then status 200
    And match responseHeaders contains {Content-Type: '#string'}
    And match response.data.account[0] contains {accountId: '#string', balance: '#[]'}
    And match response.data.account[0].balance[0] contains {type: '#string', creditDebitIndicator: '#string', amount: '#string', currency: '#string', datetime: '#string'}

    Examples:
      | read('aisp_accounts_accountId_balances_get.csv') |
