# ********RoostGPT********

# Test generated by RoostGPT for test Karate-CSV using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /aisp/account-consents/{consentId}_get for http method type GET 
# RoostTestHash=8deb268cea
# 
# 

# ********RoostGPT********
Feature: Test /aisp/account-consents/{consentId} endpoint

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase

  Scenario Outline: Test GET /aisp/account-consents/{consentId} endpoint
    Given path 'aisp', 'account-consents', '<consentId>'
    And header Authorization = karate.properties['AUTH_TOKEN']
    And header x-fapi-auth-date = '<x-fapi-auth-date>'
    And header x-fapi-customer-ip-address = '<x-fapi-customer-ip-address>'
    And header x-fapi-interaction-id = '<x-fapi-interaction-id>'
    And header Accept-Language = '<Accept-Language>'
    When method get
    Then status 200
    And match response.data == {consentId:'#string', creationDate:'#string', status:'#string', statusUpdateDate:'#string', permissions:'#[]', expirationDate:'#string', transactionFromDate:'#string', transactionToDate:'#string'}
    And match response.links == {self:'#string', prev:'#string', next:'#string'}
    And match response.headers == {x-fapi-interaction-id:'#string'}

    Examples:
      | read('aisp_account-consents_consentId_get.csv') |
