# ********RoostGPT********

# Test generated by RoostGPT for test Karate-CSV using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /aisp/accounts_get for http method type GET 
# RoostTestHash=1174086886
# 
# 

# ********RoostGPT********
Feature: Account Status API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def headers = { 'Authorization': '#(karate.properties['AUTH_TOKEN'])', 'x-fapi-auth-date': 'Sun, 10 Sep 2017 19:43:31 UTC', 'x-fapi-customer-ip-address': '169.254.169.254', 'x-fapi-interaction-id': 'id123', 'Accept-Language': 'en' }
    * configure headers = headers

  Scenario: Ensure successful account status check
    Given path '/aisp/accounts'
    When method GET
    Then status 200
    And match header Content-Type == 'application/json'
    And match response.data.account[*].accountId contains '#string'
    And match response.data.account[*].accountNumber contains '#string'
    And match response.data.account[*].accountType contains '#string'
    And match response.data.account[*].accountSubType contains '#string'
    And match response.data.account[*].productName contains '#string'
    And match response.data.account[*].accountStatus contains '#string'
    And match response.data.account[*].currency contains '#string'
    And match response.links.self contains '#string'
    And match response.links.prev contains '#string'
    And match response.links.next contains '#string'

  Scenario: Ensure unsuccessful account status check with invalid authorization
    Given path '/aisp/accounts'
    And header Authorization = 'invalid_token'
    When method GET
    Then status 401

  Scenario: Ensure unsuccessful account status check with forbidden access
    Given path '/aisp/accounts'
    And header Authorization = 'forbidden_token'
    When method GET
    Then status 403

  Scenario: Ensure unsuccessful account status check with method not allowed
    Given path '/aisp/accounts'
    When method POST
    Then status 405

  Scenario: Ensure unsuccessful account status check with not acceptable request
    Given path '/aisp/accounts'
    And header Accept-Language = 'invalid_language'
    When method GET
    Then status 406
