# ********RoostGPT********

# Test generated by RoostGPT for test Karate-CSV using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /aisp/accounts/{accountId}/transactions_get for http method type GET 
# RoostTestHash=8eaa6f6421
# 
# 

# ********RoostGPT********
Feature: Test /aisp/accounts/{accountId}/transactions endpoint

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase

  Scenario Outline: Test GET /aisp/accounts/{accountId}/transactions with valid parameters
    Given path 'aisp/accounts', '<accountId>', 'transactions'
    And header Authorization = karate.properties['AUTH_TOKEN']
    And header x-fapi-auth-date = '<x-fapi-auth-date>'
    And header x-fapi-customer-ip-address = '<x-fapi-customer-ip-address>'
    And header x-fapi-interaction-id = '<x-fapi-interaction-id>'
    And header Accept-Language = '<Accept-Language>'
    And param fromDate = '<fromDate>'
    And param toDate = '<toDate>'
    When method get
    Then status 200
    And match response.data == '#object'
    And match response.data.transaction == '#array'
    And match response.data.transaction[0] == '#object'
    And match response.links == '#object'
    And match response.links.self == '#string'
    And match response.links.prev == '#string'
    And match response.links.next == '#string'

    Examples:
      | read('aisp_accounts_accountId_transactions_get.csv') |

  Scenario Outline: Test GET /aisp/accounts/{accountId}/transactions with invalid parameters
    Given path 'aisp/accounts', '<accountId>', 'transactions'
    And header Authorization = karate.properties['AUTH_TOKEN']
    And header x-fapi-auth-date = '<x-fapi-auth-date>'
    And header x-fapi-customer-ip-address = '<x-fapi-customer-ip-address>'
    And header x-fapi-interaction-id = '<x-fapi-interaction-id>'
    And header Accept-Language = '<Accept-Language>'
    And param fromDate = '<fromDate>'
    And param toDate = '<toDate>'
    When method get
    Then status 400
    And match response.id == '#string'
    And match response.errors == '#array'
    And match response.errors[0] == '#object'
    And match response.errors[0].code == '#string'
    And match response.errors[0].causes == '#string'
    And match response.errors[0].extendedDetails == '#object'
    And match response.headers == '#object'
    And match response.headers.Content-Type == '#string'
    And match response.headers['x-fapi-interaction-id'] == '#string'

    Examples:
      | accountId | x-fapi-auth-date | x-fapi-customer-ip-address | x-fapi-interaction-id | Accept-Language | fromDate | toDate |
      | ''        | ''               | ''                         | ''                    | ''              | ''       | ''     |
