# ********RoostGPT********

# Test generated by RoostGPT for test Karate-CSV using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /aisp/account-consents_post for http method type POST 
# RoostTestHash=412472914e
# 
# 

# ********RoostGPT********
Feature: AISP Account Consents API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * def headers = {Authorization: '#(authToken)', 'Content-Type': 'application/json', 'x-fapi-auth-date': 'string', 'x-fapi-customer-ip-address': 'string', 'x-fapi-interaction-id': 'string', 'Accept-Language': 'string'}
    * configure headers = headers

  Scenario Outline: Test POST /aisp/account-consents
    Given path '/aisp/account-consents'
    And request {"data": {"permissions": ["<permission>"], "expirationDate": "<expirationDate>", "transactionFromDate": "<transactionFromDate>", "transactionToDate": "<transactionToDate>"}}
    When method post
    Then status <statusCode>
    And match response contains {data: '#object'}
    And match response.data contains {consentId: '#string', creationDate: '#string', status: '#string', statusUpdateDate: '#string'}
    And match response.data.permissions contains ['<permission>']
    And match response.data contains {expirationDate: '<expirationDate>', transactionFromDate: '<transactionFromDate>', transactionToDate: '<transactionToDate>'}
    And match response.links contains {self: '#string', prev: '#string', next: '#string'}
    And match response.headers contains {'x-fapi-interaction-id': '#string'}

    Examples:
      | read('aisp_account-consents_post.csv') |
