# ********RoostGPT********

# Test generated by RoostGPT for test Karate-Integration using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# ROOST_METHOD_HASH=ee0418c08a
# ROOST_METHOD_SIG_HASH=1c092be52c
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: WiFi Troubleshooting for Fiber Internet Customers',
#   background: 'Background:\n' +
#     '    Given the customer support representative has access to the service activation and configuration API\n' +
#     '    And the customer support representative has access to the service test management API',
#   rule: null,
#   scenario: {
#     title: 'Scenario: Diagnose and resolve WiFi interference issues',
#     steps: 'Given a customer with subscriber ID "SVTAL004" reports slow WiFi speeds\n' +
#       'When the support representative initiates a diagnostic test\n' +
#       'Then the service test API should return a test ID\n' +
#       'And the diagnostic result should indicate WiFi interference on the current channel\n' +
#       'When the support representative uses the configuration API to change the WiFi channel to an less congested one\n' +
#       'Then the configuration API should return a success response\n' +
#       'And the customer should report improved WiFi speeds',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: WiFi Troubleshooting for Fiber Internet Customers

  Background:
    * def APPOINTMENT_V2_80D7DADBB1_URL = karate.properties['APPOINTMENT_V2_80D7DADBB1_URL'] || karate.get('APPOINTMENT_V2_80D7DADBB1_URL', 'http://localhost:4010')
    * def APPOINTMENT_V2_80D7DADBB1_AUTH_TOKEN = karate.properties['APPOINTMENT_V2_80D7DADBB1_AUTH_TOKEN'] || karate.get('APPOINTMENT_V2_80D7DADBB1_AUTH_TOKEN', 'Bearer_Dummy_Token')

  Scenario: Diagnose and resolve WiFi interference issues
    * url APPOINTMENT_V2_80D7DADBB1_URL
    And path '/searchTimeSlot'
    And param subscriberId = 'SVTAL004'
    And param associatedDocument = 'WFH123'
    And param startDate = '2023-01-01T08:00:00Z'
    And param finishDate = '2023-01-01T12:00:00Z'
    And param orderType = 'ChamadoTecnico'
    And header Authorization = APPOINTMENT_V2_80D7DADBB1_AUTH_TOKEN
    When method get
    Then status 200
    And match $.control.type == 'S'
    And match $.slots == '#array'
    And match $.slots[0].id == '#string'
    And match $.slots[0].id == 'interference123'
    * url APPOINTMENT_V2_80D7DADBB1_URL
    And path '/appointment'
    And header Authorization = APPOINTMENT_V2_80D7DADBB1_AUTH_TOKEN
    And request
      """
      { 
        "appointment": { 
          "reason": "Change WiFi Channel", 
          "slot": { 
            "id": "slot789" 
          } 
        } 
      }
      """
    When method post
    Then status 201
    And match $.control.type == 'S'
    And match $.appointment.id == '#string'
