# ********RoostGPT********

# Test generated by RoostGPT for test Karate-Integration using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# ROOST_METHOD_HASH=4992e43bd0
# ROOST_METHOD_SIG_HASH=cb107cc3ec
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: WiFi Troubleshooting for Fiber Internet Customers',
#   background: 'Background:\n' +
#     '    Given the customer support representative has access to the service activation and configuration API\n' +
#     '    And the customer support representative has access to the service test management API',
#   rule: null,
#   scenario: {
#     title: 'Scenario: Enable WiFi for a new customer',
#     steps: 'Given a new customer with subscriber ID "SVTAL005" has just had their fiber service installed\n' +
#       'When the support representative uses the configuration API to enable WiFi\n' +
#       'Then the configuration API should return a success response\n' +
#       'And the customer should be able to see and connect to their new WiFi network',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: WiFi Troubleshooting for Fiber Internet Customers

  Background:
    * def APPOINTMENT_V2_80D7DADBB1_URL = karate.properties['APPOINTMENT_V2_80D7DADBB1_URL'] || karate.get('APPOINTMENT_V2_80D7DADBB1_URL', 'http://localhost:4010')
    * def APPOINTMENT_V2_80D7DADBB1_AUTH_TOKEN = karate.properties['APPOINTMENT_V2_80D7DADBB1_AUTH_TOKEN'] || karate.get('APPOINTMENT_V2_80D7DADBB1_AUTH_TOKEN', 'Bearer_Dummy_Token')

  Scenario: Enable WiFi for a new customer using appointmentConfirmation endpoint
    * url APPOINTMENT_V2_80D7DADBB1_URL
    And header Authorization = APPOINTMENT_V2_80D7DADBB1_AUTH_TOKEN
    And def payload = { appointment: { confirmation: true, id: 'SVTAL005' } }
    When path '/appointmentConfirmation'
    And request payload
    Then method post
    And status 200
    And match response.control == '#object'
    And match response.control.code == '#string'
    And match response.control.message == '#string'
    And match response.control.type == '#string'

  Scenario: Enable WiFi for a new customer using searchTimeSlot endpoint
    * url APPOINTMENT_V2_80D7DADBB1_URL
    And params { 
      addressId: '123',
      subscriberId: 'SVTAL005',
      associatedDocument: 'DOC123',
      startDate: '2023-04-01T00:00:00Z',
      finishDate: '2023-04-30T23:59:59Z',
      orderType: 'Instalacao'
    }
    When path '/searchTimeSlot'
    Then method get
    And status 200
    And match response.control == '#object'
    And match response.control.code == '#string'
    And match response.control.message == '#string'
    And match response.control.type == '#string'
    And match response.slots == '#array'
    And match response.slots[0] == '#object'
    And match response.slots[0].expireIn == '#number'
    And match response.slots[0].finishDate == '#string'
    And match response.slots[0].id == '#string'
    And match response.slots[0].startDate == '#string'
