# ********RoostGPT********

# Test generated by RoostGPT for test Karate-CSV using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /events_post for http method type POST 
# RoostTestHash=6bbed7894a
# 
# 

# ********RoostGPT********
Feature: Events API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def AUTH_TOKEN = karate.properties['AUTH_TOKEN']
    * def headers = {Authorization: '#(AUTH_TOKEN)', 'Content-Type': 'application/json'}

  Scenario Outline: Post Events
    Given path '/events'
    And headers headers
    And request {"ack":["<ack>"],"returnImmediately":<returnImmediately>,"maxEvents":<maxEvents>}
    When method post
    Then match responseStatus == <statusCode>
    And match response contains {sets:'#string', moreAvailable:'#boolean'}

    Examples:
      | read('events_post.csv') |

  Scenario Outline: Validate Headers and Error Response
    Given path '/events'
    And headers headers
    And request {"ack":["<ack>"],"returnImmediately":<returnImmediately>,"maxEvents":<maxEvents>}
    When method post
    Then match responseStatus == <statusCode>
    And match responseHeaders contains {'Content-Type':'application/json', 'x-fapi-interaction-id':'#string'}
    And match response contains {id:'#string', errors:'#[]'}

    Examples:
      | read('events_post.csv') |
