# ********RoostGPT********

# Test generated by RoostGPT for test Karate-CSV using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /aisp/accounts/{accountId}_get for http method type GET 
# RoostTestHash=8067523cbb
# 
# 

# ********RoostGPT********
Feature: Fulfilment endpoints - Account Status by Account ID

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']

  Scenario Outline: Validate account status by account ID
    Given path '/aisp/accounts/', '<accountId>'
    And header Authorization = 'Bearer ' + authToken
    And header x-fapi-auth-date = 'Sun, 10 Sep 2017 19:43:31 UTC'
    And header x-fapi-customer-ip-address = '169.254.169.254'
    And header x-fapi-interaction-id = 'UniqueID'
    And header Accept-Language = 'en-US'
    When method get
    Then status <statusCode>
    And match responseHeaders['Content-Type'] == 'application/json'
    And match responseHeaders['x-fapi-interaction-id'] == '#string'
    And match each $response.data.account[*].accountId == '#string'
    And match each $response.data.account[*].accountNumber == '#string'
    And match each $response.data.account[*].accountType == '#string'
    And match each $response.data.account[*].accountSubType == '#string'
    And match each $response.data.account[*].productName == '#string'
    And match each $response.data.account[*].accountStatus == '#string'
    And match each $response.data.account[*].currency == '#string'
    And match $response.links.self == '#string'
    And match $response.links.prev == '#string'
    And match $response.links.next == '#string'

    Examples:
      | read('aisp_accounts_accountId_get.csv') |
