# ********RoostGPT********

# Test generated by RoostGPT for test Karate-CSV using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /aisp/accounts/{accountId}/transactions_get for http method type GET 
# RoostTestHash=8eaa6f6421
# 
# 

# ********RoostGPT********
Feature: Test /aisp/accounts/{accountId}/transactions API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def AUTH_TOKEN = karate.properties['AUTH_TOKEN']

  Scenario Outline: Test GET /aisp/accounts/{accountId}/transactions API with valid inputs
    * def accountId = '<accountId>'
    * def headers = { Authorization: '#(AUTH_TOKEN)', 'x-fapi-auth-date': '<x-fapi-auth-date>', 'x-fapi-customer-ip-address': '<x-fapi-customer-ip-address>', 'x-fapi-interaction-id': '<x-fapi-interaction-id>', 'Accept-Language': '<Accept-Language>' }
    Given path '/aisp/accounts/', accountId, '/transactions'
    And params { fromDate: '<fromDate>', toDate: '<toDate>' }
    And headers headers
    When method get
    Then status 200
    And match response.data == '#object'
    And match response.data.transaction == '#array'
    And match response.data.transaction[0] == '#object'
    And match response.links == '#object'
    And match response.links.self == '#string'
    And match response.links.prev == '#string'
    And match response.links.next == '#string'

    Examples:
      | read('aisp_accounts_accountId_transactions_get.csv') |

  Scenario: Test GET /aisp/accounts/{accountId}/transactions API with invalid accountId
    * def accountId = 'invalid'
    * def headers = { Authorization: '#(AUTH_TOKEN)', 'x-fapi-auth-date': 'date', 'x-fapi-customer-ip-address': 'ip', 'x-fapi-interaction-id': 'id', 'Accept-Language': 'en' }
    Given path '/aisp/accounts/', accountId, '/transactions'
    And params { fromDate: '2021-01-01', toDate: '2021-12-31' }
    And headers headers
    When method get
    Then status 400
    And match response.id == '#string'
    And match response.errors == '#array'
    And match response.errors[0] == '#object'
    And match response.errors[0].code == '#string'
    And match response.errors[0].causes == '#string'
    And match response.errors[0].extendedDetails == '#object'
    And match response.headers == '#object'
    And match response.headers.Content-Type == '#string'
    And match response.headers['x-fapi-interaction-id'] == '#string'
