# ********RoostGPT********

# Test generated by RoostGPT for test Karate-CSV using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /aisp/account-consents/{consentId}_get for http method type GET 
# RoostTestHash=8deb268cea
# 
# 

# ********RoostGPT********
Feature: Account Consents API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def AUTH_TOKEN = karate.properties['AUTH_TOKEN']

  Scenario Outline: Validate GET /aisp/account-consents/{consentId} endpoint
    Given path '/aisp/account-consents/', '<consentId>'
    And header Authorization = AUTH_TOKEN
    And header x-fapi-auth-date = '<x-fapi-auth-date>'
    And header x-fapi-customer-ip-address = '<x-fapi-customer-ip-address>'
    And header x-fapi-interaction-id = '<x-fapi-interaction-id>'
    And header Accept-Language = '<Accept-Language>'
    When method get
    Then status <status_code>
    And match responseHeaders contains { 'x-fapi-interaction-id': '#string' }
    And match response ==
      """
      { 
        data: '#object', 
        'data.consentId': '#string', 
        'data.creationDate': '#string', 
        'data.status': '#string', 
        'data.statusUpdateDate': '#string', 
        'data.permissions': '#array', 
        'data.permissions.0': '#string', 
        'data.expirationDate': '#string', 
        'data.transactionFromDate': '#string', 
        'data.transactionToDate': '#string', 
        links: '#object', 
        'links.self': '#string', 
        'links.prev': '#string', 
        'links.next': '#string' 
      }
      """

    Examples:
      | read('aisp_account-consents_consentId_get.csv') |
