# ********RoostGPT********

# Test generated by RoostGPT for test Karate-CSV using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /aisp/accounts_get for http method type GET 
# RoostTestHash=1174086886
# 
# 

# ********RoostGPT********
Feature: Fulfilment endpoints

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def AUTH_TOKEN = karate.properties['AUTH_TOKEN']

  Scenario Outline: Test accountStatus endpoint
    * def headers = { 'Authorization': '#(AUTH_TOKEN)', 'x-fapi-auth-date': '<x-fapi-auth-date>', 'x-fapi-customer-ip-address': '<x-fapi-customer-ip-address>', 'x-fapi-interaction-id': '<x-fapi-interaction-id>', 'Accept-Language': '<Accept-Language>' }
    * path '/aisp/accounts'
    * method get
    * request { }
    * status <status_code>

    Examples:
      | read('aisp_accounts_get.csv') |
