# ********RoostGPT********

# Test generated by RoostGPT for test Karate-CSV using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /aisp/account-consents_post for http method type POST 
# RoostTestHash=412472914e
# 
# 

# ********RoostGPT********
Feature: AISP Account Consents API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase

  Scenario Outline: Test POST /aisp/account-consents endpoint
    Given path '/aisp/account-consents'
    And request
      """
      { 
        "data": { 
          "permissions": ["<permission>"], 
          "expirationDate": "<expirationDate>", 
          "transactionFromDate": "<transactionFromDate>", 
          "transactionToDate": "<transactionToDate>" 
        } 
      }
      """
    And headers
      """
      { 
        "Authorization": karate.properties['AUTH_TOKEN'], 
        "Content-Type": "application/json", 
        "x-fapi-auth-date": "<x-fapi-auth-date>", 
        "x-fapi-customer-ip-address": "<x-fapi-customer-ip-address>", 
        "x-fapi-interaction-id": "<x-fapi-interaction-id>", 
        "Accept-Language": "<Accept-Language>" 
      }
      """
    When method post
    Then status <status_code>
    And match response.data.consentId == '#string'
    And match response.data.creationDate == '#string'
    And match response.data.status == '#string'
    And match response.data.statusUpdateDate == '#string'
    And match response.data.permissions == '#array'
    And match response.data.permissions[0] == '#string'
    And match response.data.expirationDate == '#string'
    And match response.data.transactionFromDate == '#string'
    And match response.data.transactionToDate == '#string'
    And match response.links.self == '#string'
    And match response.links.prev == '#string'
    And match response.links.next == '#string'
    And match response.headers['x-fapi-interaction-id'] == '#string'

    Examples:
      | read('aisp_account-consents_post.csv') |
